# Graph parameters
network: ws
population_size: 500
num_runs: 1
load_pickle: True

# WS model parameters
ws:
  neighbours: 4
  rewire_p: 0.1


# SIRD model parameters
horizon: 200
infection_rate: 0.95
reinfection_rate: 0.0001
recovery_rate: 0.1
death_rate: 0.01
vaccination_rate: 0.001

init_state:
  I: 1
  R: 0
  D: 0
  V: 0

# paths
dir:
  pickle: 'pickle/'
  img: 'img/'